
# debug: true

logging:
  # 设置分组
  group:
    enbank: com.jiang.controller,com.jiang.service
    ali: com.alibaba

  level:
    root: info
    # 设置某个包的日志级别
    #    com.itheima.controller: debug
    # 设置分组，对某个组设置日志级别

    # com.jiang: debug
    enbank: debug

  pattern:
  #    console: "%d - %m %n"
#     console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"

  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: server.%d{yyyy-mm-dd}.%i.log

# debug: true



