# ???
# debug: true

logging:
  # ???????????????
  group:
    enbank: com.jiang.controller,com.jiang.service
    ali: com.alibaba

  level:
    root: info
    # ??????????
    # com.jiang: debug
    enbank: debug

  # ????????
  pattern:
    # %d ????
    # %clr() ????????????
    # %5p   5???????????p??????
    # %16t 16???????p??????
    # %-40.40c -40??40???????????-?????.40????????c????????,{}?????
    # %m ?????????
    # %n ????
    # console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"

  file:
    name: server.log
  logback:
    rollingpolicy: # ????
      max-file-size: 10MB
      # %d ????
      # %i ????????i???
      file-name-pattern: server.%d{yyyy-mm-dd}.%i.log

